jobmonitor:
  baseUrl: http://localhost:8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/jobmonitor
    username: postgres
    password:
