jobmonitor:
  baseUrl: http://localhost:8080
  externalApiKey: a70bf2be-432b-4273-9470-32976097bfab
  externalApiUrl: https://www.reed.co.uk/api/1.0/search

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/jobmonitor
    username: postgres
    password:
